USE RETAIL;
SELECT * FROM PRODUCT WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCT);
SELECT * FROM CUSTOMER WHERE CUSTID IN (SELECT DISTINCT CUSTID FROM ORDERS);
SELECT * FROM PRODUCT WHERE PRODID IN (SELECT DISTINCT PRODID FROM ORDERS);
SELECT * FROM ORDERS WHERE QTY > (SELECT AVG(QTY) FROM ORDERS);
SELECT * FROM SUPPLIER S WHERE EXISTS (SELECT 1 FROM PRODUCT P WHERE P.SUPID = S.SUPID AND P.PRICE > 1000);
SELECT ORDERID, PRODID, (SELECT PRICE FROM PRODUCT WHERE PRODUCT.PRODID = ORDERS.PRODID) AS Product_Price FROM ORDERS;
SELECT * FROM PRODUCT WHERE STOCK < (SELECT MAX(QTY) FROM ORDERS);
SELECT * FROM PRODUCT P WHERE STOCK < (SELECT SUM(QTY) FROM ORDERS O WHERE O.PRODID = P.PRODID);
